### ISSUE TITLE
Background image doesn't load on lightmode

### ISSUE THREAD

**Issue by concertaStan** [concertaStan/ChatPlusPlus#2]
The reason is because the mechanism for changing the background only affects dark tagged elements

**content_script.js:**
![image](https://user-images.githubusercontent.com/129684780/232177857-e7eae536-c350-4055-8450-306b5794a8ba.png)

**Comment by quantavoid11** [comment]
Hey @concertaStan, can I work on this issue?

**Comment by concertaStan** [comment]
Yeah sure!
